---
name: Specification Change
description: >-
  Propose a change to the ccpkg specification
labels: ["spec", "proposal"]
body:
  - type: markdown
    attributes:
      value: >
        Use this template to propose additions,
        modifications, or removals to the ccpkg
        specification.
  - type: dropdown
    id: change-type
    attributes:
      label: Change Type
      description: >-
        What kind of specification change
        are you proposing?
      options:
        - New section or feature
        - Modification to existing section
        - Deprecation or removal
        - Clarification of ambiguous language
    validations:
      required: true
  - type: input
    id: spec-section
    attributes:
      label: Specification Section
      description: >-
        Which section(s) of the specification
        does this affect?
      placeholder: >-
        e.g., Section 4 - Component Types
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: >-
        Brief description of the proposed change.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: >-
        Why is this change needed? What problem
        does it solve or what use case does it
        enable?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Change
      description: >-
        Describe the change in detail. Include
        proposed spec language where possible
        (using RFC 2119 keywords).
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: >-
        What other approaches were considered
        and why were they rejected?
  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: |
        Which areas does this change affect?
        - Manifest schema changes?
        - Host adapter changes?
        - Backward compatibility implications?
        - Tooling changes required?
  - type: dropdown
    id: hosts-affected
    attributes:
      label: Host Adapters Affected
      description: >-
        Which AI coding assistant adapters
        does this change affect?
      multiple: true
      options:
        - All hosts
        - Claude Code
        - GitHub Copilot
        - OpenAI Codex CLI
        - Google Gemini CLI
        - OpenCode
    validations:
      required: true
